replicaCount: 2

image:
  repository: "302263046734.dkr.ecr.us-east-1.amazonaws.com/vulcan-test"
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "ofer-devops-test.vulcancyber.com"
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:region:account-id:certificate/certificate-id"
  hosts:
    - host: "ofer-devops-test.vulcancyber.com"
      paths:
        - path: /
          pathType: ImplementationSpecific
